# -*- coding: utf-8 -*-
"""zoo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHqK2qt1V5qMPwgyUIzb2zGvyupKdmBB
"""

def hours():
  return 'Open 9-5 daily'

